services:
  nats:
    container_name: bnt-nats
    image: nats:latest
    ports:
      - "4222:14222"
      - "6222:16222"
      - "8222:18222"
    networks:
      - bnt-network

  app:
    container_name: bnt-app
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - nats
    networks:
      - bnt-network
    environment:
      - TICKER_WAIT_SECONDS=5s
      - NUMBER_OF_SUBSCRIBERS=5
      - NATS_URL=nats://nats:4222
      - NATS_SUBJECT=docker-test-subject

networks:
  bnt-network:
